# These are supported funding model platforms

patreon: lazyprog
custom: ['https://lazyprog.com', 'monero:86wYKQPiEsa5MKRM5MeqxM1eDXLtYG8w5HCHjJA7dqatE6epUgVaYB3cKjZQUv15AVggiagb8pvSt4fF1LfKryoRP8vqTMZ', 'bitcoin:bc1q8qmdkg58l5dkx9x0m53wxeqzca0pa4dghsppwk']
